### PR TITLE
[Fix/#45]: axios instance 통일, 비밀번호 변경 api 요청 수정

### PR DESCRIPTION
**Pull request by JIMIN1020**
## 📌 작업 내용
- axios instance 통일
- 비밀번호 변경 api 요청 수정 (사업자등록번호 추가)

### ✔️ axios instance
2가지 인스턴스로 나누지 않고 하나로 통일하는 방식으로 변경했습니다.

토큰이 만료되어서 401 에러가 발생했을 때 재발급을 처리하는 로직을 interceptor에 추가해두었는데, 로그인 때도 401 에러가 발생하다보니 이걸 별개의 인스턴스로 처리해야 하는 줄 알았어요..!

멘토님께 조언 듣고 나니 interceptor 내에서 로그인 여부를 판단한 뒤에, 로그인이 된 상태라면 토큰 재발급을 처리하면 되는 문제여서 기존 인스턴스에 재발급 로직만 추가하는 방식으로 변경했습니다~!

<br/>

## 📌 구현 결과 (선택)

<br/>

## 📌 기타 사항
- sessionStore에 로그인 여부를 저장할 것인지에 대한 것은 더 고민해보겠습니다

<br/>

### CODE REVIEW

**Comment by JIMIN1020** [comment]
<h2>Coverage Report</h2>
<table> <thead> <tr> <th align="center">Status</th> <th align="left">Category</th> <th align="right">Percentage</th> <th align="right">Covered / Total</th> </tr> </thead> <tbody> <tr> <td align="center">🔵</td> <td align="left">Lines</td> <td align="right">0%</td> <td align="right">0 / 3795</td> </tr> <tr> <td align="center">🔵</td> <td align="left">Statements</td> <td align="right">0%</td> <td align="right">0 / 3795</td> </tr> <tr> <td align="center">🔵</td> <td align="left">Functions</td> <td align="right">2.06%</td> <td align="right">3 / 145</td> </tr> <tr> <td align="center">🔵</td> <td align="left">Branches</td> <td align="right">2.06%</td> <td align="right">3 / 145</td> </tr> </tbody> </table><details><summary>File Coverage</summary><table> <thead> <tr> <th align="left">File</th> <th align="right">Stmts</th> <th align="right">% Branch</th> <th align="right">% Funcs</th> <th align="right">% Lines</th> <th align="left">Uncovered Lines</th> </tr> </thead> <tbody> <tr> <td align="left" colspan="6"><b>Changed Files</b></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/auth.api.ts">src/api/auth.api.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/auth.api.ts#L1" class="text-red">1</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/auth.api.ts#L3-L10" class="text-red">3-10</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/auth.api.ts#L12-L22" class="text-red">12-22</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts">src/api/http.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L1-L5" class="text-red">1-5</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L7-L13" class="text-red">7-13</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L15-L24" class="text-red">15-24</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L26-L32" class="text-red">26-32</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L34-L41" class="text-red">34-41</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L43" class="text-red">43</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L45-L60" class="text-red">45-60</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L62-L63" class="text-red">62-63</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/api/http.ts#L65" class="text-red">65</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/CatalogDetail/api/liquor.api.ts">src/features/CatalogDetail/api/liquor.api.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/CatalogDetail/api/liquor.api.ts#L1" class="text-red">1</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/CatalogDetail/api/liquor.api.ts#L3-L10" class="text-red">3-10</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/CatalogDetail/api/register.api.ts">src/features/CatalogDetail/api/register.api.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/CatalogDetail/api/register.api.ts#L1" class="text-red">1</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/CatalogDetail/api/register.api.ts#L3-L6" class="text-red">3-6</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/CatalogDetail/api/register.api.ts#L9-L17" class="text-red">9-17</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/api/findPassword.api.ts">src/features/FindPassword/api/findPassword.api.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/api/findPassword.api.ts#L1" class="text-red">1</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/api/findPassword.api.ts#L3" class="text-red">3</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/api/findPassword.api.ts#L6-L8" class="text-red">6-8</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/api/findPassword.api.ts#L10" class="text-red">10</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/api/findPassword.api.ts#L13-L15" class="text-red">13-15</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/hooks/useFindPassword.ts">src/features/FindPassword/hooks/useFindPassword.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/hooks/useFindPassword.ts#L1-L4" class="text-red">1-4</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/hooks/useFindPassword.ts#L7-L11" class="text-red">7-11</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/hooks/useFindPassword.ts#L13-L22" class="text-red">13-22</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/hooks/useFindPassword.ts#L24-L33" class="text-red">24-33</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/hooks/useFindPassword.ts#L35-L47" class="text-red">35-47</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/FindPassword/hooks/useFindPassword.ts#L49-L50" class="text-red">49-50</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts">src/features/Join/api/signup.api.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts#L1-L3" class="text-red">1-3</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts#L5" class="text-red">5</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts#L7-L9" class="text-red">7-9</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts#L11-L14" class="text-red">11-14</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts#L16-L18" class="text-red">16-18</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts#L20-L23" class="text-red">20-23</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Join/api/signup.api.ts#L25-L34" class="text-red">25-34</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Login/api/login.api.ts">src/features/Login/api/login.api.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Login/api/login.api.ts#L1-L2" class="text-red">1-2</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Login/api/login.api.ts#L6-L15" class="text-red">6-15</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Login/api/login.api.ts#L17-L23" class="text-red">17-23</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Profile/api/getProfile.ts">src/features/Profile/api/getProfile.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Profile/api/getProfile.ts#L1" class="text-red">1</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Profile/api/getProfile.ts#L3-L6" class="text-red">3-6</a></td> </tr> <tr> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Profile/api/putProfile.ts">src/features/Profile/api/putProfile.ts</a></td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="right">0%</td> <td align="left"><a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Profile/api/putProfile.ts#L1" class="text-red">1</a>, <a href="https://github.com/Licruit/Licruit-frontend/blob/eaa730aa250a3d22b9d8e760e194ecd305601015/src/features/Profile/api/putProfile.ts#L4-L7" class="text-red">4-7</a></td> </tr> </tbody> </table></details>
<em>Generated in workflow <a href=https://github.com/Licruit/Licruit-frontend/actions/runs/10295574021>#64</a></em>

**Review by juhee067 — APPROVED** [review]
확인했습니다. 저도 같이 고민해볼게요!

**Review by SebellKo — APPROVED** [review]
지민님 고생 하셨습니다 ~
로그인은 이렇게 하는거군요

**Review by ksy90101 — COMMENTED** [review]
Good!

**Pull request merged**
